package view;

import controller.CtrlConta;
import controller.CtrlExtrato;
import Utilitario.TransferenciaContas;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Tela extends javax.swing.JFrame {

    private Connection conexao;
    int ctrl = 0;
        
    public Tela() {
        initComponents();
        carregarTabelaConta();
        modoInativo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBanco = new javax.swing.JTabbedPane();
        jPaConta = new javax.swing.JPanel();
        jBNovo = new javax.swing.JButton();
        jBGrava = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBExtrato = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableContas = new javax.swing.JTable();
        jTFNumero = new javax.swing.JTextField();
        jTFAgencia = new javax.swing.JTextField();
        jTFSaldo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPaExtrato = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableExtrato = new javax.swing.JTable();
        jBEExcluir = new javax.swing.JButton();
        jPTransferencia = new javax.swing.JPanel();
        jTFContaOrigem = new javax.swing.JTextField();
        jTFValorTransferencia = new javax.swing.JTextField();
        jTFContaDestino = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jBTransferir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBNovo.setText("Novo");
        jBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNovoActionPerformed(evt);
            }
        });

        jBGrava.setText("Gravar");
        jBGrava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGravaActionPerformed(evt);
            }
        });

        jBEditar.setText("Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBExtrato.setText("Extrato");
        jBExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExtratoActionPerformed(evt);
            }
        });

        jTableContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Número", "Agência", "Saldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableContas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableContasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableContas);

        jLabel1.setText("Número Conta");

        jLabel2.setText("Agência");

        jLabel3.setText("Saldo");

        javax.swing.GroupLayout jPaContaLayout = new javax.swing.GroupLayout(jPaConta);
        jPaConta.setLayout(jPaContaLayout);
        jPaContaLayout.setHorizontalGroup(
            jPaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaContaLayout.createSequentialGroup()
                .addGroup(jPaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaContaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1))
                    .addGroup(jPaContaLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(jPaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103)
                        .addGroup(jPaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTFAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106)
                        .addGroup(jPaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPaContaLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jBNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jBGrava, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jBEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jBExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPaContaLayout.setVerticalGroup(
            jPaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaContaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaContaLayout.createSequentialGroup()
                        .addGroup(jPaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(10, 10, 10)
                        .addGroup(jPaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaContaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(jTFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(jPaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBNovo)
                        .addComponent(jBGrava))
                    .addComponent(jBEditar)
                    .addComponent(jBExcluir)
                    .addComponent(jBExtrato))
                .addGap(22, 22, 22))
        );

        jPBanco.addTab("Conta", jPaConta);

        jTableExtrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Data", "Tipo", "Valor", "Código Conta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableExtrato);

        jBEExcluir.setText("Excluir");
        jBEExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaExtratoLayout = new javax.swing.GroupLayout(jPaExtrato);
        jPaExtrato.setLayout(jPaExtratoLayout);
        jPaExtratoLayout.setHorizontalGroup(
            jPaExtratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaExtratoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPaExtratoLayout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jBEExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPaExtratoLayout.setVerticalGroup(
            jPaExtratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaExtratoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jBEExcluir)
                .addContainerGap())
        );

        jPBanco.addTab("Extrato", jPaExtrato);

        jLabel4.setText("Conta Origem");

        jLabel10.setText("Valor");

        jLabel11.setText("Conta Destino");

        jBTransferir.setText("Transferir");
        jBTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTransferirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPTransferenciaLayout = new javax.swing.GroupLayout(jPTransferencia);
        jPTransferencia.setLayout(jPTransferenciaLayout);
        jPTransferenciaLayout.setHorizontalGroup(
            jPTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTransferenciaLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(jPTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBTransferir)
                    .addGroup(jPTransferenciaLayout.createSequentialGroup()
                        .addGroup(jPTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFContaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(84, 84, 84)
                        .addGroup(jPTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jTFContaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(79, 79, 79)
                .addGroup(jPTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFValorTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPTransferenciaLayout.setVerticalGroup(
            jPTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTransferenciaLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPTransferenciaLayout.createSequentialGroup()
                        .addGroup(jPTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFContaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFContaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPTransferenciaLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFValorTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63)
                .addComponent(jBTransferir)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jPBanco.addTab("Transferencia", jPTransferencia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBanco)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBanco)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modoInativo(){
        jTFNumero.setEnabled(false);
        jTFAgencia.setEnabled(false);
        jTFSaldo.setEnabled(false);
    }
    
    private void modoAtivo(){
        jTFNumero.setEnabled(true);
        jTFAgencia.setEnabled(true);
        jTFSaldo.setEnabled(true);
    }
    
    private void gravaConta(){
        String[] dados = new String[4];
        int iLinha = jTableContas.getSelectedRow();
        
        if (ctrl == 0) {
            dados[0] = "0";
            dados[1] = jTFNumero.getText();
            dados[2] = jTFAgencia.getText();
            dados[3] = jTFSaldo.getText();
            CtrlConta.inserir(dados);
        } 
        else {
            dados[0] = (String) jTableContas.getValueAt(iLinha, 0);
            dados[1] = jTFNumero.getText();
            dados[2] = jTFAgencia.getText();
            dados[3] = jTFSaldo.getText();
            CtrlConta.inserir(dados);
        }
    }
    
    private void jBGravaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGravaActionPerformed
        gravaConta();
        carregarTabelaConta();
        modoInativo();
    }//GEN-LAST:event_jBGravaActionPerformed

    private void jBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoActionPerformed
        jTFNumero.setText("");
        jTFAgencia.setText("");
        jTFSaldo.setText("");
        ctrl = 0;
        modoAtivo();
    }//GEN-LAST:event_jBNovoActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        int codigoConta = Integer.parseInt((String) jTableContas.getValueAt(jTableContas.getSelectedRow(), 0));
            
        if (codigoConta >= 0) {
            if(JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o registro? ") == 0){
                CtrlConta.excluir(codigoConta);
            }
        }
        carregarTabelaConta();
        modoInativo();
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jTableContasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableContasMousePressed
        jTFNumero.setText((String) jTableContas.getValueAt(jTableContas.getSelectedRow(), 1));
        jTFAgencia.setText((String) jTableContas.getValueAt(jTableContas.getSelectedRow(), 2));
        jTFSaldo.setText((String) jTableContas.getValueAt(jTableContas.getSelectedRow(), 3));
    }//GEN-LAST:event_jTableContasMousePressed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        ctrl = 1;
        modoAtivo();
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBEExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEExcluirActionPerformed
        int codigoExtrato = Integer.parseInt((String) jTableExtrato.getValueAt(jTableExtrato.getSelectedRow(), 0));
        if (codigoExtrato >= 0) {
            if(JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o registro? ") == 0){
                CtrlExtrato.excluir(codigoExtrato);
            }
        }
        carregarTabelaExtrato();
    }//GEN-LAST:event_jBEExcluirActionPerformed

    private void jBExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExtratoActionPerformed
        carregarTabelaExtrato();
    }//GEN-LAST:event_jBExtratoActionPerformed

    private void jBTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTransferirActionPerformed
        int codContaOrigem = Integer.parseInt(jTFContaOrigem.getText());
        int codContaDestino = Integer.parseInt(jTFContaDestino.getText());
        double valor = Double.parseDouble(jTFValorTransferencia.getText());
        
        try {
            TransferenciaContas.transferir(codContaOrigem, codContaDestino, valor);
        } catch (SQLException ex) {
            System.out.println("Erro ao tentar transferir - view " + ex);
        }
        
        carregarTabelaConta();
    }//GEN-LAST:event_jBTransferirActionPerformed
    
    private void carregarTabelaConta(){
        DefaultTableModel model = (DefaultTableModel) jTableContas.getModel();
        model.setNumRows(0);

        String[][] lista = CtrlConta.recuperarTodos();

        for (String[] dado : lista) {
            model.addRow(dado);
        }
    }
    
    private void carregarTabelaExtrato(){

        int codConta = Integer.parseInt((String) jTableContas.getValueAt(jTableContas.getSelectedRow(), 0));
        DefaultTableModel model = (DefaultTableModel) jTableExtrato.getModel();
        model.setNumRows(0);

        String[][] lista = CtrlExtrato.recuperarExtratoConta(codConta);

        for (String[] dado : lista) {
            model.addRow(dado);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEExcluir;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBExtrato;
    private javax.swing.JButton jBGrava;
    private javax.swing.JButton jBNovo;
    private javax.swing.JButton jBTransferir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTabbedPane jPBanco;
    private javax.swing.JPanel jPTransferencia;
    private javax.swing.JPanel jPaConta;
    private javax.swing.JPanel jPaExtrato;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFAgencia;
    private javax.swing.JTextField jTFContaDestino;
    private javax.swing.JTextField jTFContaOrigem;
    private javax.swing.JTextField jTFNumero;
    private javax.swing.JTextField jTFSaldo;
    private javax.swing.JTextField jTFValorTransferencia;
    private javax.swing.JTable jTableContas;
    private javax.swing.JTable jTableExtrato;
    // End of variables declaration//GEN-END:variables
}
